# Merge Datasets

In [17]:
import pandas as pd
import numpy as np
import re

### Load Full Dataset

In [18]:
df_full = pd.read_csv('../data/full_nonrookie.csv')
df_full.head()

,fullName,term,signAge,contractLength,totalValue,aav,isEntryLevel,signSeason,Tm,G,...,DBPM_prev2,BPM_prev2,VORP_prev2,height,weight,birthDate,draftRound,draftOverall,draftYear,undrafted
0,Carmelo Anthony,2014-2018,30.0,5,124064681.0,24812936.0,0,2013-14,NYK,77,...,-0.2,3.6,2.7,79,238,1984-05-29,1,3,2003,False
1,Carmelo Anthony,2018-2018,34.0,1,2393887.0,2393887.0,0,2017-18,OKC,78,...,-0.5,3.3,3.4,79,238,1984-05-29,1,3,2003,False
2,Carmelo Anthony,2020-2020,36.0,1,2564753.0,2564753.0,0,2019-20,POR,58,...,-1.3,-1.9,0.0,79,238,1984-05-29,1,3,2003,False
3,Carmelo Anthony,2021-2021,37.0,1,2641691.0,2641691.0,0,2020-21,POR,69,...,-1.4,-2.7,-0.1,79,238,1984-05-29,1,3,2003,False
4,Chris Bosh,2014-2018,29.0,5,118705300.0,23741060.0,0,2013-14,MIA,79,...,-0.2,0.8,1.4,83,235,1984-03-24,1,4,2003,False

### Load Awards

In [19]:
df_awds = pd.read_csv('../data/playerCumulativeAwards.csv')
df_awds.rename({'name': 'fullName', 'season': 'signSeason'}, axis=1, inplace=True)
df_awds.head()

,fullName,signSeason,allDEF1stTeam,allDEF2ndTeam,allNBA1stTeam,allNBA2ndTeam,allNBA3rdTeam,allROOKIE1stTeam,allROOKIE2ndTeam,allStar,assistChamp,dpoy,mip,mvp,nbaChamp,reboundChamp,roy,scoreChamp,smoy
0,A.C. Green,1986-87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,A.C. Green,1987-88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
2,A.C. Green,1988-89,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
3,A.C. Green,1989-90,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
4,A.C. Green,1999-00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0

### Merge

In [20]:
df = df_full.merge(df_awds, on=['fullName', 'signSeason'], how='left').fillna(0)
df.head()

,fullName,term,signAge,contractLength,totalValue,aav,isEntryLevel,signSeason,Tm,G,...,allStar,assistChamp,dpoy,mip,mvp,nbaChamp,reboundChamp,roy,scoreChamp,smoy
0,Carmelo Anthony,2014-2018,30.0,5,124064681.0,24812936.0,0,2013-14,NYK,77,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Carmelo Anthony,2018-2018,34.0,1,2393887.0,2393887.0,0,2017-18,OKC,78,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Carmelo Anthony,2020-2020,36.0,1,2564753.0,2564753.0,0,2019-20,POR,58,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Carmelo Anthony,2021-2021,37.0,1,2641691.0,2641691.0,0,2020-21,POR,69,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,Chris Bosh,2014-2018,29.0,5,118705300.0,23741060.0,0,2013-14,MIA,79,...,9.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0

In [31]:
cols = ['fullName', 'signSeason', 'totalValue', 'aav', 'nbaChamp', 'allStar',
        'allNBA1stTeam', 'allNBA2ndTeam', 'allNBA3rdTeam']
# df[df['fullName']=='Kevin Love'][cols]
# df[df['fullName']=='Paul George'][cols]
# df[df['fullName']=='Kawhi Leonard'][cols]
df[df['fullName']=='Chris Paul'][cols]

,fullName,signSeason,totalValue,aav,nbaChamp,allStar,allNBA1stTeam,allNBA2ndTeam,allNBA3rdTeam
1027,Chris Paul,2017-18,159730592.0,39932648.0,0.0,9.0,4.0,3.0,1.0
1028,Chris Paul,2020-21,120000000.0,30000000.0,0.0,11.0,4.0,5.0,1.0

### Save dataset

In [32]:
df.to_csv('../data/full_nonrookie_w_awards.csv', index=False)